--INICIO DATASET LKDV
WITH CTE_PROCESOCARGA_100 AS(
SELECT
DESPROCESOCARGA || '_' || DESMODULOPROCESOCARGA || '_' || NUMSECUENCIAEJECUCION AS KEY_PROCESO,
CODJOBSCHED,
CASE WHEN NBRPROCESOCARGA='LKDV_DUMMY' THEN 'SI' ELSE 'NO' END AS ES_DUMMY
FROM ADMIN.CT_PROCESOCARGA
)
--SELECT * FROM CTE_PROCESOCARGA_100
,CTE_EJECUCION_100 AS(
SELECT
DESPROCESOCARGA || '_' || DESMODULOPROCESOCARGA || '_' || NUMSECUENCIAEJECUCION AS KEY_PROCESO,
--FECHORAINICIOEJECUCION,
--FECHORAFINEJECUCION,
--CONVERTIR A SECUNDOS LOS CAMPOS FECHORAINICIOEJECUCION Y FECHORAFINEJECUCION PARA POSTERIORMENTE APLICAR AVG
DECODE(EXTRACT(HOUR FROM FECHORAINICIOEJECUCION), 0, 24, EXTRACT(HOUR FROM FECHORAINICIOEJECUCION))*3600+ EXTRACT(MINUTE FROM FECHORAINICIOEJECUCION)*60 + EXTRACT(SECOND FROM FECHORAINICIOEJECUCION) AS CC_TRANS_SECONDS_FECINICIO,
DECODE(EXTRACT(HOUR FROM FECHORAFINEJECUCION), 0, 24, EXTRACT(HOUR FROM FECHORAFINEJECUCION))*3600+ EXTRACT(MINUTE FROM FECHORAFINEJECUCION)*60 + EXTRACT(SECOND FROM FECHORAFINEJECUCION) AS CC_TRANS_SECONDS_FECFIN
FROM ADMIN.CT_EJECUCIONPROCESOCARGA
WHERE FECHORAINICIOEJECUCION >= TO_TIMESTAMP('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')
)
--SELECT * FROM CTE_EJECUCION_100
,CTE_EJECUCION_110 AS(
--AGRUPAR LOS REG Y APLICAR AVG A LOS CAMPOS FECHORAINICIOEJECUCION Y FECHORAFINEJECUCION
SELECT KEY_PROCESO,AVG(CC_TRANS_SECONDS_FECINICIO) AS CC_PROM_FECINICIO,AVG(CC_TRANS_SECONDS_FECFIN) AS CC_PROM_FECFIN FROM CTE_EJECUCION_100 GROUP BY KEY_PROCESO
)
--SELECT * FROM CTE_EJECUCION_110							  
,CTE_EJECUCION_120 AS(
SELECT
KEY_PROCESO,
TO_CHAR(NUMTODSINTERVAL(CC_PROM_FECINICIO, 'SECOND'), 'HH24:MI:SS.FF') AS PROM_FECINICIO,
TO_CHAR(NUMTODSINTERVAL(CC_PROM_FECFIN, 'SECOND'), 'HH24:MI:SS.FF') AS PROM_FECFIN,
TO_CHAR(NUMTODSINTERVAL(CC_PROM_FECFIN - CC_PROM_FECINICIO, 'SECOND'), 'HH24:MI:SS.FF') AS PROM_DURACION
FROM CTE_EJECUCION_110
)
--SELECT * FROM CTE_EJECUCION_120
,CTE_JOIN_PROCESOCARGA_EJECUCION_LKDV AS(
SELECT A.KEY_PROCESO,A.CODJOBSCHED,A.ES_DUMMY,B.PROM_FECINICIO,B.PROM_FECFIN,B.PROM_DURACION 
FROM CTE_PROCESOCARGA_100 A
LEFT JOIN CTE_EJECUCION_120 B ON A.KEY_PROCESO=B.KEY_PROCESO
)
--SELECT * FROM CTE_JOIN_PROCESOCARGA_EJECUCION_LKDV
--FIN DATASET LKDV

--INICIO DATASET LHCL
,CTE_PROCESOCARGA_LHCL_100 AS(
SELECT 
DESPROCESOCARGA || '_' || DESMODULOPROCESOCARGA || '_' || NUMSECUENCIAEJECUCION AS KEY_PROCESO,
CODJOBSCHED,
--NBRPROCESOCARGAJOB,
CASE WHEN NBRPROCESOCARGAJOB='LHCL_DUMMY' THEN 'SI' ELSE 'NO' END AS ES_DUMMY
FROM ADMIN.CT_PROCESOCARGA_LHCL
)
--SELECT * FROM CTE_PROCESOCARGA_LHCL_100
,CTE_EJECUCION_LHCL_100 AS(
SELECT
DESPROCESOCARGA || '_' || DESMODULOPROCESOCARGA || '_' || NUMSECUENCIAEJECUCION AS KEY_PROCESO,
--FECHORAINICIOEJECUCION,
--FECHORAFINEJECUCION,
--CONVERTIR A SECUNDOS LOS CAMPOS FECHORAINICIOEJECUCION Y FECHORAFINEJECUCION PARA POSTERIORMENTE APLICAR AVG																											  
DECODE(EXTRACT(HOUR FROM FECHORAINICIOEJECUCION), 0, 24, EXTRACT(HOUR FROM FECHORAINICIOEJECUCION))*3600+ EXTRACT(MINUTE FROM FECHORAINICIOEJECUCION)*60 + EXTRACT(SECOND FROM FECHORAINICIOEJECUCION) AS CC_TRANS_SECONDS_FECINICIO,
DECODE(EXTRACT(HOUR FROM FECHORAFINEJECUCION), 0, 24, EXTRACT(HOUR FROM FECHORAFINEJECUCION))*3600+ EXTRACT(MINUTE FROM FECHORAFINEJECUCION)*60 + EXTRACT(SECOND FROM FECHORAFINEJECUCION) AS CC_TRANS_SECONDS_FECFIN
FROM ADMIN.CT_EJECUCIONPROCESOCARGA_LHCL 
WHERE FECHORAINICIOEJECUCION >= TO_TIMESTAMP('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')
)
--SELECT * FROM CTE_EJECUCION_LHCL_100
,CTE_EJECUCION_LHCL_110 AS(
SELECT KEY_PROCESO,AVG(CC_TRANS_SECONDS_FECINICIO) AS CC_PROM_FECINICIO,AVG(CC_TRANS_SECONDS_FECFIN) AS CC_PROM_FECFIN FROM CTE_EJECUCION_LHCL_100 GROUP BY KEY_PROCESO
)
--SELECT * FROM CTE_EJECUCION_LHCL_110
,CTE_EJECUCION_LHCL_120 AS(
SELECT
KEY_PROCESO,
TO_CHAR(NUMTODSINTERVAL(CC_PROM_FECINICIO, 'SECOND'), 'HH12:MI:SS.FF AM') AS PROM_FECINICIO,
TO_CHAR(NUMTODSINTERVAL(CC_PROM_FECFIN, 'SECOND'), 'HH12:MI:SS.FF AM') AS PROM_FECFIN,
TO_CHAR(NUMTODSINTERVAL(CC_PROM_FECFIN - CC_PROM_FECINICIO, 'SECOND'), 'HH12:MI:SS.FF AM') AS PROM_DURACION
FROM CTE_EJECUCION_LHCL_110
)
--SELECT * FROM CTE_EJECUCION_LHCL_120
,CTE_JOIN_PROCESOCARGA_EJECUCION_LHCL AS(
SELECT A.KEY_PROCESO,A.CODJOBSCHED,A.ES_DUMMY,B.PROM_FECINICIO,B.PROM_FECFIN,B.PROM_DURACION FROM CTE_PROCESOCARGA_LHCL_100 A
LEFT JOIN CTE_EJECUCION_LHCL_120 B ON A.KEY_PROCESO=B.KEY_PROCESO
)
--FIN DATASET LHCL
--SELECT * FROM CTE_JOIN_PROCESOCARGA_EJECUCION_LHCL

--FULL OUTER JOIN LKDV-LHCL
SELECT 
A.KEY_PROCESO,A.CODJOBSCHED,A.ES_DUMMY,
REGEXP_SUBSTR(A.PROM_FECINICIO, '\d{2}:\d{2}:\d{2}\.\d+') AS PROM_FECINICIO,
REGEXP_SUBSTR(A.PROM_FECFIN, '\d{2}:\d{2}:\d{2}\.\d+') AS PROM_FECFIN,
REGEXP_SUBSTR(A.PROM_DURACION, '\d{2}:\d{2}:\d{2}\.\d+') AS PROM_DURACION,

B.KEY_PROCESO AS KEY_PROCESO_LHCL,B.CODJOBSCHED AS CODJOBSCHED_LHCL ,A.ES_DUMMY AS ES_DUMMY_LHCL,
REGEXP_SUBSTR(B.PROM_FECINICIO, '\d{2}:\d{2}:\d{2}\.\d+') AS PROM_FECINICIO_LHCL,
REGEXP_SUBSTR(B.PROM_FECFIN, '\d{2}:\d{2}:\d{2}\.\d+') AS PROM_FECFIN_LHCL,
REGEXP_SUBSTR(B.PROM_DURACION, '\d{2}:\d{2}:\d{2}\.\d+') AS PROM_DURACION_LHCL
FROM CTE_JOIN_PROCESOCARGA_EJECUCION_LKDV A
FULL OUTER JOIN CTE_JOIN_PROCESOCARGA_EJECUCION_LHCL B ON A.KEY_PROCESO = B.KEY_PROCESO
ORDER BY 
    CASE 
        WHEN A.KEY_PROCESO IS NOT NULL AND B.KEY_PROCESO IS NOT NULL THEN 1 -- Coinciden en ambas tablas
        WHEN A.KEY_PROCESO IS NOT NULL THEN 2 -- Solo en LKDV
        WHEN B.KEY_PROCESO IS NOT NULL THEN 3 -- Solo en LHCL
        ELSE 4 -- Ambas nulas
    END,
    COALESCE(A.KEY_PROCESO, B.KEY_PROCESO) ASC;

--SELECT COUNT(*) FROM ADMIN.CT_PROCESOCARGA 9943
--SELECT COUNT(*) FROM ADMIN.CT_PROCESOCARGA_LHCL 9492

/*
--DUPLICADOS ADMIN.CT_PROCESOCARGA
SELECT 'ADMIN.CT_PROCESOCARGA' AS ORIGEN,A.*
FROM ADMIN.CT_PROCESOCARGA A
WHERE UPPER(DESPROCESOCARGA) IN (
    SELECT UPPER(DESPROCESOCARGA)
    FROM ADMIN.CT_PROCESOCARGA
    GROUP BY UPPER(DESPROCESOCARGA), UPPER(DESMODULOPROCESOCARGA), UPPER(NUMSECUENCIAEJECUCION)
    HAVING COUNT(1) > 1
) 
--DUPLICADOS ADMIN.CT_PROCESOCARGA_LHCL
SELECT 'ADMIN.CT_PROCESOCARGA_LHCL' AS ORIGEN,A.*
FROM ADMIN.CT_PROCESOCARGA_LHCL A
WHERE UPPER(DESPROCESOCARGA) IN (
    SELECT UPPER(DESPROCESOCARGA)
    FROM ADMIN.CT_PROCESOCARGA_LHCL
    GROUP BY UPPER(DESPROCESOCARGA), UPPER(DESMODULOPROCESOCARGA), UPPER(NUMSECUENCIAEJECUCION)
    HAVING COUNT(1) > 1
) 
*/

